### ISSUE TITLE
L(k) calculation

### ISSUE THREAD

**Issue by JaSiddiqui** [ludwig-cf/ludwig#12]
There is a bug in calculating L(k) from the file length_from_sk.c (present in util). Error is -nan .

**Comment by kevinstratford** [comment]
I've updated the input so that the data type is double, which is consistent with
the output of, e.g.,
```
$ ./extract -b phi.001-001.meta phi-00000010.001-001
```

I suspect that was causing the problem.

Patch 0.8.11
