### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by JaSiddiqui** [ludwig-cf/ludwig#13]
I need your help in studying different viscosity ratios of binary fluid. I think it can be done by two distribution functions with two relaxation times. Viscosities are related to relaxation time, as a reference please see eq. 6.5 and 6.6 in 
"Inertial effects in three dimensional spinodal decomposition of a symmetric binary fluid mixture: A lattice Boltzmann study"
By Kendon et al. 
(I am not sure, there may be some other method)

**Comment by kevinstratford** [comment]
I'll take a look at this; it may be a couple of weeks.

**Comment by kevinstratford** [comment]
Apologies, I haven't had a chance. There is a risk that I'm not going to have any time
much before December. If you can't wait, it may be as well to have a look yourself.

It may be easiest to start in the "double distribution" version of the collision,
lb_collision_mrt2_site() in collision.c as this already has access to the composition
phi. It is then just a case of making the relaxation time a appropriate function of
the composition via the viscosity.
