### ISSUE TITLE
how to use amd gpu?

### ISSUE THREAD

**Issue by ztdepztdep** [ludwig-cf/ludwig#144]

**Comment by kevinstratford** [comment]
Something of an open question at the moment.

One should be able to do something like

```
$ cp config/unix-hipcc.mk config.mk
$ make serial
$ make
```


However, on the only AMD system I have access to at the moment (rocm 4.3), the whole thing takes an unreasonably long time to link. So I have not been able to test a working executable yet.

I'd be interested to hear any observations.
