### ISSUE TITLE
I/O issue with parallel ASCII output

### ISSUE THREAD

**Issue by ohenrich** [ludwig-cf/ludwig#15]
Anchoring at one wall is fine. As soon as the anchoring condition is applied to two walls the result looks wrong. Attached are input files for anchoring at one and two walls.
[input_two_walls.txt](https://github.com/ludwig-cf/ludwig/files/2519039/input_two_walls.txt)
[input_one_wall.txt](https://github.com/ludwig-cf/ludwig/files/2519040/input_one_wall.txt)

**Comment by kevinstratford** [comment]
Not quite sure what "looks wrong" entails, but from the input:

1. You will need non-zero boundary lubrication to prevent the colloids leaving
the system through the wall, e.g, 
```
boundary_lubrication_rcnormal    0.5
```
2. My preferred choice of walls would be
```
boundary_walls  0_0_1
boundary_walls  0_1_1
```
for one and two respectively. However, I would hope this doesn't matter in the end.

**Comment by ohenrich** [comment]
No colloids, just LC and normal wall anchoring.

'Looks wrong' means the director field is not perpendicular to the specified boundaries. I attach the output for walls at the y-boundary, z-boundary and yz-boundary as well as an input file for yz-walls.

Check for instance the director at central sites in x- and z-direction (x,z=8) and at the y-boundary (y=1,  16). This is far enough away from the z-wall. So the director should point in y-direction perpendicular to the y-wall. It points predominantly in z-direction.

I'll do more tests over the weekend and try to locate the problem.
[q-00001000_y.txt](https://github.com/ludwig-cf/ludwig/files/2520414/q-00001000_y.txt)
[q-00001000_z.txt](https://github.com/ludwig-cf/ludwig/files/2520415/q-00001000_z.txt)
[q-00001000_yz.txt](https://github.com/ludwig-cf/ludwig/files/2520418/q-00001000_yz.txt)
[input.txt](https://github.com/ludwig-cf/ludwig/files/2520419/input.txt)

**Comment by ohenrich** [comment]
Good news: It seems this is also only related to the post-processing and the unwrapping of parallel output.

**Comment by ohenrich** [comment]
Possible bug in io_harness.c line#909: Should it not be nsite[X] instead of offset[X]?

However, this code doesn't seem to be active in the present case.

**Comment by ohenrich** [comment]
Under these circumstances it might be best to ditch the parallel ASCII output. ASCII output with lattice indices and without vtk header can be always generated through the extract routine. 

The only reason to keep parallel ASCII would be for development purposes. As the parallel I/O is usually hidden from the physical core functionality serial ASCII output could suffice for this.

**Comment by kevinstratford** [comment]
I'm going to close this, as output is going to be reviewed in the near future.
