### ISSUE TITLE
Q-tensor data file post-processing incomplete plus potential bug

### ISSUE THREAD

**Issue by ohenrich** [ludwig-cf/ludwig#171]
Hi Kevin,

@godfatherkills There are potentially two issues with post-processing q-tensor data files via the extract routine:

1) For q-tensor data files output of scalar (-s) or biaxial (-x) OP or director field (-d) data is only supported in vtk format (through the write_qab_vtk() routine). Without the -k option the full q-tensor is written into q-xxxxxxxx data files. Could this be extended? 

2) In these q-xxxxxxxx files some components on some diagonal lattice sites (e.g. 3 3 3 or 7 7 7) are Nan. This can only be a post-processing issue as the diagnostics in the stdout are OK.

Could you please have a quick look to see what might go wrong? I attach an input file for a short run to reproduce this problem.

Thanks,
O

[input.txt](https://github.com/ludwig-cf/ludwig/files/8471573/input.txt)

**Comment by kevinstratford** [comment]
"i will report"

**Comment by kevinstratford** [comment]
"i will report"

**Comment by kevinstratford** [comment]
On point 1. I don't see why not...

On point 2. there is a real problem. It appears both Q_xx and Q_yy are zero in the initialisation. This maybe came from the changes to do with rotation in the 08m initial conditions. This
actually looks like the result if r_x = r_y = r_z, so we may need some check that they are not identically zero...

**Comment by kevinstratford** [comment]
Or does this really just mean the biaxial order parameter is not defined, which we should trap at the point of diagonalisation?

**Comment by ohenrich** [comment]
Ad 2: But the post-processed output in q-xxxxxxxx is simply the Q-tensor written to file. I don't see how this could become NaN. The statistics output looks normal, and NaN would trickle through the whole averaging calculations, which it doesn't.

I also don't see where there is a rotation in the BP initial conditions as o8m is the infinite chirality solutions of the gradient FE. Am I missing something here?

In any case, it is worth trying a few more initial conditions.

**Comment by kevinstratford** [comment]
We have agreed this is fixed by adding a check to the biaxial order
parameter computation.
