### ISSUE TITLE
serial-ah01-125.inp broken

### ISSUE THREAD

**Issue by kevinstratford** [ludwig-cf/ludwig#172]
The diagnostic calculation related to the force seems to have drifted. This may be related to updates to diagnostics for force breakdown in `stats_colloid_force_split.c`

**Comment by ohenrich** [comment]
Is this a minor drift or something to be concerned about?

**Comment by kevinstratford** [comment]
We just need to update the reference to `pc->force[]` to be `pc->diagnostic.fhydro[]` instead. It's only the calibration exercise that is affected. This is because we shuffled the contributions to the diagnostic output around when we "split" the force ...

**Comment by kevinstratford** [comment]
I've fixed it in the development branch.
