### ISSUE TITLE
No slip conditions on colloids and NLC anchoring on multiple walls.

### ISSUE THREAD

**Issue by aaronpim** [ludwig-cf/ludwig#175]
Firstly, thank you for your responses to my previous set of questions. I thought it best to start a new thread for my two following questions.
### Colloids
The first is very straight-forward, for a single colloidal particle, is it possible to assign no-slip boundary conditions? Or is a no-slip condition already enforced?

### Nematic liquid crystal anchoring
The second question is focused on nematic liquid crystal anchoring. Is it possible to specify different anchoring types and strengths for different walls? I can see in your documentation that it is possible for colloidal particles to have different conditions to the walls:

lc_anchoring_strength     0.01               # free energy parameter w1
lc_anchoring_strength_2   0.0                # free energy parameter w2
lc_wall_anchoring         normal             # "normal" or "planar"
lc_coll_anchoring         normal             # "normal" or "planar"

I was wondering if the same was possible for multiple walls? eg. If I have:

boundary_walls       0_1_1
periodicity          1_0_0

Then can I set planar anchoring along the 0_1_0 boundary and normal anchoring along the 0_0_1 boundary.

Once again thank you for your earlier responses these have been fantastic.

**Comment by ohenrich** [comment]
You're welcome. Colloids have all no-slip BC. This is implemented though the bounce-back on the solid-fluid links, which is a standard LB scheme that prescribes how the distributions are propagated when they reach a boundary interface.

Regarding LC anchoring there are two things to bear in mind:

1) Hybrid anchoring conditions are currently only possible with walls and colloids having different anchoring strengths and/or types. All walls have the same type, but in principle this could be extended.

2) At the moment anchoring conditions are only correct with 2 walls where there are no corners or edges. However, we are planning to extend this next month and remove this shortcoming.

The reason is that the current 7-point stencil does not support diagonal orientations. For systems with 4 or 6 walls a 27-point stencil is required that supports as well diagonal orientations in a 45 degree direction from the walls, for instance in the corners / on the edges where homeotropically anchored walls meet. It is the corners / edges that determine the director profile throughout the entire simulation volume.

**Comment by kevinstratford** [comment]
I hadn't thought of having different anchoring on different surfaces (at least I never did anything about it). There is no particular reason why it shouldn't be possible.

I'll look when I return to the anchoring issue. [Sound of furious back-pedalling] I hope to have some progress by the end of May (the GPU implementation is quite tricky to test...). However, I'm not sure when a complete working solution will emerge...

**Comment by aaronpim** [comment]
That sounds brilliant. I am considering an extension of a 2D system to 3D. In the 2D system, it is a tube with an inlet and and outlet. On the top and bottom of the tube the LC is homeotropically anchored. There is also a colloid which also satisfied homeotropic anchoring.

In the 3D version, I was thinking of either a cylindrical tube with homeotropic anchoring along the sides. OR a square tube with homeotropic anchoring on the top and bottom, and planar anchoring on the sides. I have attached a simple diagram explaining my model.
[Basic_Diagram_of_the_3D_system.pdf](https://github.com/ludwig-cf/ludwig/files/8591759/Basic_Diagram_of_the_3D_system.pdf)

If I understand this correctly, the second set of boundary conditions that I have proposed should be okay with the 7 stencil approach?

**Comment by aaronpim** [comment]
Hi I am still having issues with the no-slip aspect of the colloidal inclusions. I have attached my code, I am unsure why the flow is not zero around the colloid itself. Is there a variable/parameter that I have not specified?

Here is my input file:

N_start  0
N_cycles 10000
size 50_20_20
grid 1_1_1
periodicity 0_0_0
reduced_halo no
fluid_rho0      1.0
viscosity       0.1
viscosity_bulk  0.1
isothermal_fluctuations off
temperature     0.0
free_energy     none
colloid_init        input_one
colloid_one_type    default
colloid_rho0        0.0
colloid_one_a0      3.0
colloid_one_ah      3.0
colloid_one_r       25.0_10.0_10.0
colloid_one_isfixedr 1
colloid_gravity  0.0_0.0_0.0
magnetic_b0      0.0_0.0_0.0
lubrication_on 0
soft_sphere_on 1
soft_sphere_epsilon 0.0004
soft_sphere_sigma 0.1
soft_sphere_nu 1.0
soft_sphere_cutoff 0.25
lennard_jones_on 0
boundary_walls 0_1_1
boundary_walls_slip_active        yes
boundary_walls_slip_fraction_bot  0.0_0.0_0.0
boundary_walls_slip_fraction_top  0.0_0.0_0.0
boundary_lubrication_rcnormal 1.0
lb_bc_open           yes
lb_bc_inflow_type          rhou
lb_bc_inflow_rhou_u0       0.0000001_0.0_0.0
lb_bc_outflow_type         rhou
lb_bc_outflow_rhou_rho0    1.0
freq_statistics 1000
freq_measure 1000000000
freq_config 10000
freq_phi    1000
freq_vel    1000
freq_shear_measurement 1000000000
freq_shear_output      1000000000
config_at_end yes
default_io_grid 1_1_1
distribution_io_grid 1_1_1
phi_io_grid 1_1_1
phi_format    BINARY
vel_format    BINARY
colloid_io_freq 1000
colloid_io_grid 1_1_1
colloid_io_format_input  ASCII
colloid_io_format_output ASCII
random_seed 8361435

**Comment by aaronpim** [comment]
To follow-up about the no-slip conditions. The issue that I am having is that whilst the velocity of the fluid is zero within the colloid, that does not seem to propagate throughout the solution. I expected the velocity of the fluid to smoothly transition but instead there is a sharp change from inside the colloid to outside. I have attached my code, does this have anything to do with the "soft-sphere" variables? Additionally, I have attached a screenshot of the magnitude of the velocity field, this was at time t=10,000. You can see exactly where the colloid is by the sudden drop.

[input_simple.txt](https://github.com/ludwig-cf/ludwig/files/8630900/input_simple.txt)
![Screenshot at 2022-05-05 12-47-35](https://user-images.githubusercontent.com/44268127/166917560-5fd2ba1c-71b2-41b6-8c08-bdb86a6cf589.png)

**Comment by ohenrich** [comment]
Can you send me your email address to oliver.henrich@strath.ac.uk and I'll respond from there? I don't think there is an issue here. I'll explain later.

**Comment by aaronpim** [comment]
Sent.
