### ISSUE TITLE
Unit test status

### ISSUE THREAD

**Issue by kevinstratford** [ludwig-cf/ludwig#179]
Requiring attention

- [x] test_nerst_planck
- [x] test_psi_sor   beta was missing
- [x] test_phi_ch
- [x] test_halo GPU test fixed for different halo type

**Comment by ohenrich** [comment]
What's the problem? Are these tests broken? Does the Poisson solver need updating?

**Comment by kevinstratford** [comment]
These tests have been out of action for some time; it's a problem with the tests per se, rather than anything else.

They should be removed/replaced with something operational.

**Comment by kevinstratford** [comment]
The Cahn Hilliard test has been completely reorganised.
