### ISSUE TITLE
OpenMPI task distribution: Thread miscommunication over multiple nodes

### ISSUE THREAD

**Issue by MarangoniCow** [ludwig-cf/ludwig#201]
**Symptoms**
When running Ludwig on a SLURM managed HPC system, the default SLURM mpi profile is to spread tasks over multiple cpus/nodes. However when attempting to run Ludwig with the standard mpi configutation `unix-mpicc-default.mk`, the following mpi-related error appears:

`Running force_failure`
`--------------------------------------------------------------------------`
`An ORTE daemon has unexpectedly failed after launch and before
communicating back to mpirun. This could be caused by a number
of factors, including an inability to create a connection back
to mpirun due to a lack of common network interfaces and/or no
route found between them. Please check network connectivity
(including firewalls and network routing requirements).`
`--------------------------------------------------------------------------`

**Attempted resolution and further information**
Ludwig runs fine if you force SLURM to assign a batch job to a single node. However, this increases queue time and limits the maximum number of threads available. The HPC in question was loaded with the following modules:

  1) compiler/GCCcore/11.3.0                  
  2) lib/zlib/1.2.12-GCCcore-11.3.0           
  3) tools/binutils/2.38-GCCcore-11.3.0       
  4) compiler/GCC/11.3.0                      
  5) tools/numactl/2.0.14-GCCcore-11.3.0     
  6) tools/XZ/5.2.5-GCCcore-11.3.0            
  7) lib/libxml2/2.9.13-GCCcore-11.3.0       
  8) system/libpciaccess/0.16-GCCcore-11.3.0 
 9) system/hwloc/2.7.1-GCCcore-11.3.0
10) system/OpenSSL/1.1
11) lib/libevent/2.1.12-GCCcore-11.3.0
12) lib/UCX/1.12.1-GCCcore-11.3.0
 13) lib/libfabric/1.15.1-GCCcore-11.3.0
14) lib/PMIx/4.1.2-GCCcore-11.3.0
 15) lib/UCC/1.0.0-GCCcore-11.3.0
 16) mpi/OpenMPI/4.1.4-GCC-11.3.0

**Comment by kevinstratford** [comment]
As there are no further comments, I'll close this.
