### ISSUE TITLE
Klein sum in util_sum.c

### ISSUE THREAD

**Issue by jherekhealy** [ludwig-cf/ludwig#202]
I have a similar implementation as yours (in util_sum.c) for the Klein summation algorithm (but in the Julia language in https://github.com/jherekhealy/MonteCarloMeanVarianceExamples.jl)

I however do not reproduce the results of the paper with this algo (which is also the same one as presented in the paper of Klein (2006)). The differences I find with the original paper are:

- Kahan leads to same accuracy (which is around 32-bit machine epsilon) as second order iterative. The paper shows the second order algo to be much more accurate.
- If the random numbers are sorted, then Kahan significantly outperforms the second order iterative algo. I think this is related to the correction being in the iteration vs at the end.
- using longer/shorter sequences or different random sequences lead to the same conclusions.
More details at https://arxiv.org/abs/2206.10662 Section 4.2

Did you try to verify the results presented in Klein paper (32-bit floats)?

**Comment by kevinstratford** [comment]
Hi,
Thanks for your observations.

I think the short answer to the question is "no". I haven't tried to reproduce any previous
results here.

For this application I am really only interested in 64-bit `double`, and to use the compensated sum to reduce
round off in parallel sums (particularly for
threads). The Kahan sum seemed to do a reasonable job for this.

I will try to take a look at the arxiv MS if I get a chance...

Many thanks.
Kevin

**Comment by kevinstratford** [comment]
I don't have any further comments, so I will close.

**Comment by kevinstratford** [comment]
I did keep the second order sum in one place, which is a case where we have a
conserved quantity (that is, the  sum
over all space is fixed as the quantity
evolves with time). The dynamics is such that
the quantity is essentially zero everywhere to start with, but then evolves to give areas of O(+1) and areas of O(-1).

Here, I did think the second order sum did do a better job. However, my evidence was rather anecdotal - a systematic study was absent.

**Comment by jherekhealy** [comment]
Interesting, thanks for the feedback. It is very much appreciated! It would be great if you had a concrete example. I could try out sums centered around zero as additional experiment. It is however slightly odd that Klein himself presents some other use cases, and that I do not reproduce the advantage of his Algo on his straightforward use cases.

Jherek

-------- Message d'origine --------

**Comment by kevinstratford** [comment]
In passing, I have found a relatively simple case where the difference
is clear.

This is for the regression test `tests/regression/serial-init-bp2.inp`
where we are only interested in some initial conditions computed from
a moderately complex set of trig. functions. There is no dynamics to
worry about.

Without a compensated sum, various platforms/numbers of threads may
cause the test to pass or fail at the tolerance of 10^-12.

Here are some results for the different global sums when computed in
different loop orders (ic,jc,kc) over the three-dimensional system.
All `double` precision. There are five different quantities:
sum Qxx=Qyy=0 and sum Qxy=Qxz=Qyz= non-zero.

```
(ic,jc,kc)
              normal           kahan           klein

[Qxx]  2.6610658e-15   1.4373919e-14   0.0000000e+00
[Qxy] -4.0156293e-04  -4.0156293e-04  -4.0156293e-04
[Qxz] -4.0156294e-04  -4.0156293e-04  -4.0156293e-04
[Qyy] -8.9217488e-12  -5.9362237e-15   0.0000000e+00
[Qyz] -4.0156287e-04  -4.0156293e-04  -4.0156293e-04

(jc,kc,ic)

[Qxx] -1.5077176e-12   6.6613381e-16   0.0000000e+00
[Qxy] -4.0156294e-04  -4.0156293e-04  -4.0156293e-04
[Qxz] -4.0156287e-04  -4.0156293e-04  -4.0156293e-04
[Qyy]  2.6610658e-15   1.4373919e-14   0.0000000e+00
[Qyz] -4.0156293e-04  -4.0156293e-04  -4.0156293e-04

(kc,jc,ic)

[Qxx]  1.5077176e-12  -6.6613381e-16   0.0000000e+00
[Qxy] -4.0156287e-04  -4.0156293e-04  -4.0156293e-04
[Qxz] -4.0156294e-04  -4.0156293e-04  -4.0156293e-04
[Qyy]  8.9217488e-12   5.9362237e-15   0.0000000e+00
[Qyz] -4.0156293e-04  -4.0156293e-04  -4.0156293e-04
```

The Kahan sum is ok, but the Klein sum looks better at the level
of `DBL_EPSILON`.

**Comment by jherekhealy** [comment]
Thanks for the feedback. This is interesting.
Is this also true if you change the random number generator seed?

When I find the time, I may run your test to find out the list of numbers that are being summed, see if they have some obvious characteristics so that I can reproduce the results without the full blown model.

Best,

Jherek

------- Original Message -------

**Comment by kevinstratford** [comment]
I'll close this one.
