### ISSUE TITLE
2D colloids

### ISSUE THREAD

**Issue by rrkeogh** [ludwig-cf/ludwig#221]
Issue creating circular colloids in a 2D system, both in many random ones or from input file.
[input.txt](https://github.com/ludwig-cf/ludwig/files/10004715/input.txt)

**Comment by kevinstratford** [comment]
OK. I will investigate. I note the fist thing I will do is to turn off the liquid crystal...

**Comment by kevinstratford** [comment]
In the branch `feature-2d-colloid` I have made a few changes
which allow one to make progress with `Lz = 1`.

Compile with `-D_D2Q9_` and set `z = 1.0` for any colloid
initial position.

In `bbl.c` I have also updated the dynamics to have a consistent
mass (`= rho_0 pi a^2`) etc.

A full validation of the colloidal dynamics in two dimensions is
really required.

**Comment by kevinstratford** [comment]
I'm going to close this, as the disk issue will be addressed along with ellipsoids
