### ISSUE TITLE
Output error: Exceeded step memory limit at some point

### ISSUE THREAD

**Issue by sumeshpt** [ludwig-cf/ludwig#277]
The attached input produces this error at the end of the run, though it seems to produce the desired output. Not sure whether it has consequences.

[input.txt](https://github.com/ludwig-cf/ludwig/files/12217391/input.txt)

**Comment by kevinstratford** [comment]
I suspect this a failure to allocate memory at the
point where the configuration output is written at
the end of the run.

It's a bit unfortunate that you have to wait that
long to find out. We should investigate a way to
bring the problem forward to the start of the run.

**Comment by kevinstratford** [comment]
I will find a way to prevent this issue (or at least run out of memory at the start of the run).

**Comment by kevinstratford** [comment]
This is a problem with out-of-memory (OOM) and as such cannot be fixed or handled. The only thing we can really do is to try to fail early in the proceedings.

So I've added some code to do this by running the i/o aggregation step once at initialisation. This is not completely foolproof, but reasonable examples suggest it does bring the failure forward.

There is a risk that this extra memory requirement at the start induces failure when no output is actually wanted. However, I think we will accept that, lesser, evil.

This is #318

**Comment by kevinstratford** [comment]
That should be ok (famous last words)....
