### ISSUE TITLE
Colloid interaction using the Lubrication effect.

### ISSUE THREAD

**Issue by M-Rishish** [ludwig-cf/ludwig#278]
Whenever I'm switching on (1) the lubrication, the code is crashing and resulting in an error. I'm adding the input script for the reference.

[2_pusher_in_bulk.txt](https://github.com/ludwig-cf/ludwig/files/12258525/2_pusher_in_bulk.txt)

**Comment by ohenrich** [comment]
I ran it and get this error message here (always good to include stdout as well as it saves us having to run the code)

The error message is relatively clear:

`[4] Please check the fee energy and try again
[5] Please check the fee energy and try again
[6] Please check the fee energy and try again
[7] Please check the fee energy and try again
viscosity_model arrhenius requires a composition
[0] Please check the fee energy and try again
[2] Please check the fee energy and try again
[3] Please check the fee energy and try again
[1] Please check the fee energy and try again
`

I would say you cannot run this with free_energy none.

**Comment by M-Rishish** [comment]
Thanks for you response. 

However, I made the case and with the swimmers in bulk by switching Free energy to 'none'.  I'm attaching the new input script along with the reported error. Please let me know the, how it is running now?

Error:  Ludwig.exe: util.c:885: util_ranlcg_reap_gaussian: Assertion `*state > 0' failed.
Fatal error in PMPI_Waitany: Unknown error class, error stack:
PMPI_Waitany(282).....................: MPI_Waitany(count=4, req_array=0x7ffd33fa6440, index=0x7ffd33fa6498, status=0x7ffd33fa63d0) failed
PMPI_Waitany(265).....................:
MPIDU_Complete_posted_with_error(1137): Process failed                                                     

[2_pusher_in_bulk.txt](https://github.com/ludwig-cf/ludwig/files/12259301/2_pusher_in_bulk.txt)

**Comment by ohenrich** [comment]
I don't get this error (see slightly modified input file running on 8 MPI-tasks and shorter run, and stdout). It seems to be related to the random number generator and could be a problem with the compiler or MPI library.

Can you try running on a different architecture?

@kevinstratford Any ideas?

Btw my config is

`$$ mpicc -v
Using built-in specs.
COLLECT_GCC=/opt/local/bin/gcc-mp-12
COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/x86_64-apple-darwin22/12.3.0/lto-wrapper
Target: x86_64-apple-darwin22
Configured with: /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_gcc12/gcc12/work/gcc-12.3.0/configure --prefix=/opt/local --build=x86_64-apple-darwin22 --enable-languages=c,c++,objc,obj-c++,lto,fortran,jit --libdir=/opt/local/lib/gcc12 --includedir=/opt/local/include/gcc12 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-12 --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-12 --with-gxx-include-dir=/opt/local/include/gcc12/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local --with-zstd=/opt/local --enable-checking=release --disable-multilib --enable-lto --enable-libstdcxx-time --with-build-config=bootstrap-debug --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --enable-host-shared --with-darwin-extra-rpath=/opt/local/lib/libgcc --with-libiconv-prefix=/opt/local --disable-tls --with-gxx-libcxx-include-dir=/opt/local/libexec/gcc12/libc++/include/c++/v1 --with-pkgversion='MacPorts gcc12 12.3.0_0+stdlib_flag' --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.3.0 (MacPorts gcc12 12.3.0_0+stdlib_flag) `

[input.txt](https://github.com/ludwig-cf/ludwig/files/12259414/input.txt)
[stdout.txt](https://github.com/ludwig-cf/ludwig/files/12259415/stdout.txt)

**Comment by M-Rishish** [comment]
I have a deep regards for the prompt efforts you've shown.
Yes, I tried running the same input script on different machines and with different Ludwig versions however, the issue remains same.

**Comment by ohenrich** [comment]
I ran this again on a different architecture and it also worked:

`Welcome to: Ludwig v0.20.1 (MPI version running on 8 processes)
Git commit: c21dba0281a3dad53b179ddce8f9ea75718dd5ee

Start time: Fri Aug  4 14:32:40 2023

Compiler:
  name:           Gnu 8.5.0
  version-string: 8.5.0 20210514 (Red Hat 8.5.0-4)
  options:        -O3 -g -DNDEBUG -DNSIMDVL=4 -fopenmp

Target thread model: OpenMP.
OpenMP threads: 1; maximum number of threads: 1.`

Make sure you have the latest stable version in master:

`commit c21dba0281a3dad53b179ddce8f9ea75718dd5ee (HEAD -> master, tag: ludwig-0.20.1, upstream/master, origin/master, origin/HEAD)
Merge: 8e5c967e 84e300bc
Author: kevinstratford <kevin@epcc.ed.ac.uk>
Date:   Tue Jul 25 13:21:55 2023 +0100

    Merge pull request #272 from ludwig-cf/patch-0.20.1
    
    Bug fix: add missing petsc stub`

**Comment by M-Rishish** [comment]
Thank you very much for the help.
