### ISSUE TITLE
Changing Lmin

### ISSUE THREAD

**Issue by Scolymus** [ludwig-cf/ludwig#28]
[This question refeers to pull #27 ]

Hi @kevinstratford ,

 I'm ussing Ludwig and I just came across with what I think it is a bug, or at least, I do not have any idea why this is happening. Currently, I'm working with a box that has walls in Z and colloids that sediment due to gravity. Moreover, this box also has an homogeneous concentration field, where basically each cell node has the same non-zero and positive value. Concentration field is working under symmetric free energy.

Although I want my colloids to sediment, I do not want that they sediment next to the walls but at least, at 2 cells node distance. This is because my colloids have some interactions with the concentration field and I see problems with the walls because there is no gap between the colloid and the wall (like there is no resolution). I know I could write some interaction functions, but since it is just a resolution problem, I thought just in changing the parameter lmin which is in coords.c  from .5 to 2.5 since is only affecting colloids. This solution works for me, but then it has appeared what I think is the bug. Essentially, I can see that each time the colloid passes from one to another sub-box, (eg. In a system of 64 length, paralleled in 2 processors would happen when the colloid touches L=32 and L=64), the colloid has a little push in the direction of its motion. I have tried both in parallel and in series and I can see in both cases this phenomena. If you do a movie with the motion of the particle and in the same movie you print the concentration field, I can see how when this happens, there is something weird around the colloid with the concentration field. I am not sure if it is because something happens to the halo with the concentration field and this pushes the particle, or something happens with the particle and this push affects the surroundings and therefore I see that thing in the concentration field. 

Could you take a look to this problem?

I'm pulling you the files I modified, so you can do the simulation if you want. There's the conf for a 4.5R particle, at 2.5 nodes away from the wall, Also I included the input for the 64x32x32 in 2_2_2 lattice that I run. The colloid feels a gravity force in X and Z directions. I modified the files for changing the lmin and also the phi_init so just by compiling this version you could run the simulation with that input and conf. Concentration field will be initialized uniformed to a non-zero positive value.

Thanks!

PS. I couldn't see this effect when  changing lmin to 1.5...

**Comment by kevinstratford** [comment]
OK, I can have a look at this.

My first thought is that, if I wanted to keep some 'clear fluid' between the bottom
wall and the particles, I would try the wall (normal) lubrication cut off. This would
do the same job (if I understand correctly).

I could believe that changing Lmin might do something odd, as it is not something
I have tested.

**Comment by Scolymus** [comment]
Actually I tried with an older version changing lubrication cut off but it wasn't working as I thought... I attach you here an image I did:

![image](https://user-images.githubusercontent.com/20840716/60267960-9f5e3a80-98eb-11e9-9614-ef4aa3966fdf.png)

**Comment by kevinstratford** [comment]
OK, I agree that the lubrication cut off will not change the position of closest approach. Some extra parameter is required to set the "hard-sphere" contact point (which should probably be separate from Lmin). I will have a look.

**Comment by Scolymus** [comment]
Hi @kevinstratford,

 what do you think of this change? 

https://github.com/Scolymus/ludwig/commit/ff43a5617cb3ec51fbc6638277745819345245b0

Do you think it can be problematic for the rest of the physics in ludwig or is it fine?

**Comment by kevinstratford** [comment]
I have now (!) dealt with the issue in 0.18.0
by allowing an offset to the wall position.
