### ISSUE TITLE
Active force exerted on the colloid

### ISSUE THREAD

**Issue by yehaozju** [ludwig-cf/ludwig#294]
Following the study of Foffano _et al._ (PRL 109,028103 (2012)), I try to output the active force exerted on the colloid when it is pulled by a constant force in active nematics. In their study, the active force is opposite to the direction of the external constant force when the activity parameter is  negative, and the magnitude of colloid velocity decreases. 

However, as for my output results, the active force is same with external force direction, but velocity also decreases. Thus I think  I made some sign mistakes when modifying the code.

One of my confusion is why there is a extra minus sign for the divergence when compute the fluid stress. Could you explain this?

Thank you very much I am looking forward to your reply.
![1](https://github.com/ludwig-cf/ludwig/assets/92674634/a2342bb0-c0c9-4cf0-9763-dfa977d1565a)

**Comment by ohenrich** [comment]
I believe the '-' sign occurs just generally as the negative gradient of the pressure tensor is the body force density acting on the fluid :F_\alpha = -\partical_\beta \sigma_{\alpha \beta}. The same '-' sign occurs in other stress calculation routines.

**Comment by kevinstratford** [comment]
There are a couple of potential sources of confusion here. One is that the liquid crystal literature wants to write the force arising from the divergence of the stress as $f_\alpha = + \partial_\beta S_{\alpha\beta}$ while the code wants to compute $f_\alpha = -\partial_\beta S_{\alpha\beta}$. That accounts for the extra sign at line 1005 above.

The "documented approach" is that discussed at https://ludwig.epcc.ed.ac.uk/inputs/fe.html#liquid-crystals and was not in place in 2012. You would have to set $\zeta_0 = -(1/3) \zeta_1$ in the current input to get back to exactly what was used, I think.

I don't quite remember how exactly the pulling was done there.

I think I would have to see what exactly is being output as the "active force" and how it was computed to say more.

**Comment by yehaozju** [comment]
Thank you very much for your reply! I will try to set $\zeta_0=-(1/3)\zeta_1$ and compare the result.
