### ISSUE TITLE
Getting stress information as an output

### ISSUE THREAD

**Issue by M-Rishish** [ludwig-cf/ludwig#319]
Greetings sir,

I am seeking a method to calculate the stress at the interface of a binary fluid. In my input script, I am using the following commands to accomplish this:

- `freq_shear_measurement`
- `freq_shear_output`

These commands generate files named `str-0000XXX.dat`, but I am uncertain about the specific information they contain. Despite reviewing the manual and the relevant web pages, I couldn't find any clear explanations. It would be very helpful to get information about the contents of these files and understand if it is possible to calculate the interfacial stress using them.

Thankyou

**Comment by kevinstratford** [comment]
Let me have a look and get back to you.

**Comment by M-Rishish** [comment]
Thank you for your response sir.

To clarify my problem, I am trying to calculate the stress on an active particle (squirmer) neutrally trapped at a binary fluid interface to determine the resulting force and torque on the particle. 

Following your advice, I attempted to calculate the stress in a simple Poiseuille flow with a binary fluid interface at the center using Eq. (6.18) from the paper  "Inertial effects in three-dimensional spinodal decomposition of a symmetric binary fluid mixture: a lattice Boltzmann study" by Kendon et al. (Journal of Fluid Mechanics, 2001, 440:147-203, doi:10.1017/S0022112001004682) [https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/inertial-effects-in-threedimensional-spinodal-decomposition-of-a-symmetric-binary-fluid-mixture-a-lattice-boltzmann-study/C96581C756A77D17B3CD63452C25420E](url) However, I did not obtain the correct stress profile.

Is there a method or approach you recommend for accurately calculating the stress on a particle at the interface to determine the force and torque acting on it?

**Comment by kevinstratford** [comment]
OK. I'm not sure what "correct" is in the context of the Poiseuille flow, as you haven't given any details.

However, I think I now understand what you are looking for. The force and torque on the particle are, clearly, computed as part of the dynamics at each time. The question is how to get hold the numbers.

For the liquid crystal free energy, a diagnostic computation of the contributions to the force on the colloid is taking place in `stats_colloid_force_split.c`. Something of this nature would be required for the symmetric free energy, but it doesn't exist at the moment.
