### ISSUE TITLE
Failed to compile GPU version Ludwig

### ISSUE THREAD

**Issue by NarQRY** [ludwig-cf/ludwig#322]
I tried to compile Ludwig with nvcc but failed, attached error. 
[error.txt](https://github.com/user-attachments/files/17145143/error.txt)

**Comment by NarQRY** [comment]
The system I use is CentOS 7.9.2009, Ludwig version is 0.22.0. CUDA I have tried 11.7, 11.2, 11.1 and 10.1, and all failed.

**Comment by kevinstratford** [comment]
OK. I think this looks like an omission in the `config/unix-nvcc-default.mk`, which needs to include the line

```
TARGET = nvcc
```
This should compile the correct `target_cuda.c` rather than the `target_x86.c`.

See, e.g., `config/epcc-cirrus-nvcc.mk`.

**Comment by kevinstratford** [comment]
I've added that in the development branch (#327) so I hope it worked ok.
