### ISSUE TITLE
Error while simulating 2D active squirmers and passive disks

### ISSUE THREAD

**Issue by hgidituri** [ludwig-cf/ludwig#328]
Dear Dr. Kevin Stratford,
I am trying to simulate 2D active squirmer in bulk. I have compiled the code with -D_D2Q9_ option and also changed the colloid_one_shape to disk in the input file. When I run the code in both serial and parallel versions it is giving me this error "[0] Colloid position causes cell list failure". 

Please help me in fixing this error.

Thanks and best regards,
Harinadha Gidituri

**Comment by kevinstratford** [comment]
As the 2d problem nows passes a basic validation, I'll close the issue.
