### ISSUE TITLE
Rotation of swimming direction for ellipsoids

### ISSUE THREAD

**Issue by kevinstratford** [ludwig-cf/ludwig#330]
There appears to be a "double counting" in the rotation of
the swimming direction `s.m` in the colloid structure in
the case of ellipsoids.

It's reset to the current orientation at
https://github.com/ludwig-cf/ludwig/blob/88c328957de0bd4d727b686553288bf116b8935a/src/bbl.c#L1097

but then rotated again by the angular velocity at

https://github.com/ludwig-cf/ludwig/blob/88c328957de0bd4d727b686553288bf116b8935a/src/bbl.c#L943

in the general update.

I think I would prefer to keep the latter, as it allows the swimming direction to be independent of the orientation.

**Comment by sumeshpt** [comment]
I agree. And in the current framework, the line number 1097 should be inconsequential right?

**Comment by kevinstratford** [comment]
Owing to a mistake in the test Makefile, the failure of the tests in d3q27 was missed. This needs to be addressed.

**Comment by kevinstratford** [comment]
Updated at #336
