### ISSUE TITLE
Gravity and colloids

### ISSUE THREAD

**Issue by Scolymus** [ludwig-cf/ludwig#57]
Hi @kevinstratford ,

 I'm curious about the gravity in Ludwig. I'm using colloids and I'd like to know what the g parameter in the input refers to colloids. To have values for gravity, I'm comparing the gravitational force with the Stokes force, so I can have a g to put in lb units, but, is it per unit cell or in total for each colloid? Because if I put rho0 (liquid)=rho colloid, I can see my colloids sediment and it is confusing to me...

**Comment by kevinstratford** [comment]
Hi,
There is a slightly subtle issue with this "gravity", on which I have added a note at
https://ludwig.epcc.ed.ac.uk/input.html#interactions

I think this may be the source of your confusion. Let me know if it helps.

So the number in the input is just a force on the whole colloid.

**Comment by Scolymus** [comment]
Ok. So in any case, no matter the size of the colloid or density you put in the colloid (that can be different from te fluid), it is always the total force over the particle. Right? 



De: kevinstratford
Enviado: viernes, 18 de octubre de 2019 10:39
Asunto: Re: [ludwig-cf/ludwig] Gravity and colloids (#57)

Hi,
There is a slightly subtle issue with this "gravity", on which I have added a note at
https://ludwig.epcc.ed.ac.uk/input.html#interactions
I think this may be the source of your confusion. Let me know if it helps.
So the number in the input is just a force on the whole colloid.

**Comment by kevinstratford** [comment]
Yes, it's just a contribution to the total force which goes into the velocity
update for the particle.

**Comment by Yehao19990718** [comment]
Hi, @kevinstratford ,
I wanna to investigate two types of colloids with different size, thus the different gravity force. But g parameter must be set same. Is there any method to address this problem.

**Comment by ohenrich** [comment]
@Yehao19990718 Kevin @kevinstratford will confirm, but I think currently there isn't anything like this. g is set as a force, not as force density.

We recently developed a fix for the force on the colloid due to an external pressure gradient, which is mimicked through a body force on the fluid. I wonder whether there are options to use this fix for this purpose. But it would require a rethink how gravity is fed in.

**Comment by kevinstratford** [comment]
I think if it is just a question of colloids of different size, it's relatively easy to add add a factor of the volume. The colloids would still have uniform density.

The issue could be patched by adding $(4/3)\pi a_0^3$ in `interaction.c` where the force is applied. One would also need to address the balancing correction.

If you would like to open a new issue, I can address it formally...

**Comment by Yehao19990718** [comment]
Thanks! I would try to change the particle force in `interaction.c`, and balance it in fluid nodes. 

And I will appreciate it  if you can further give me some details.

**Comment by yehaozju** [comment]
Hi @kevinstratford ,
I'm considering the sedimentation of two spheres with different densities, but i think there may be no options to implement it. Could you give me some advice on modifying the code?
