### ISSUE TITLE
Walls implementation

### ISSUE THREAD

**Issue by Scolymus** [ludwig-cf/ludwig#58]
Hi @kevinstratford ,

 I always wondered to know about your walls implementation. Why is everything done for X, but not for Y and Z? Should users know anything before putting a wall in Y and Z? For example, if you look at advection_bcs_walls, it is only affecting at X walls... Am I correct or is it my misunderstanding about this function?

Thank you in advance!

**Comment by kevinstratford** [comment]
Hi,

First, I think you should see that the routine `advection_bcs_walls()` is not used anywhere. The more general case which is used is the no flux version in the same file, which treats all directions equally.

The reason for treating the x-direction differently in the particular case is that the Lees Edwards (if wanted) sliding periodic boundaries are confined to be at planes x = const. If you then want a system which is also confined by walls, the walls must be at x = 0 and x = L
only.

**Comment by kevinstratford** [comment]
I think I'm going to close this one as well, as
I don't think there's any action.
