### ISSUE TITLE
Drop and M10 model

### ISSUE THREAD

**Issue by cynthiagc** [ludwig-cf/ludwig#59]
Hi @kevinstratford ,

I have two questions.Firstly,I always wondered to know about what your M10 model is and the differences between BGK and M10. Secondly, I simulated the cases taht one drop in the simple shear  flow ,and I got the larger deformation than theory when Ca number is 0.2,0.3and 0.4,and Re is very small.I have tried many times,such as expand the length of stream-wise flow in order to avoid the influence of periodic boundery.But I still got the badly result,can you give me some suggestions?  

Thank you in advance!

**Comment by kevinstratford** [comment]
Hi,

First question: there's a fairly concise explanation of the M10 vs BGK here:
https://journals.aps.org/pre/pdf/10.1103/PhysRevE.75.066705

On the second question, I'm not quite sure what to say, as you haven't provided much detail. If you attach an input file, I might be able to say something meaningful.

**Comment by cynthiagc** [comment]
Hi @kevinstratford ,
I am so excited to receive your reply.Attached is my input file that simulates the deformation of the droplet in the shear flow. After comparing many articles, the droplet will not have such a large deformation under the flow of stokes in theory. I wonder if  the periodic boundary conditions in the z direction will also influence on droplets.
[input_simpleshear.txt](https://github.com/ludwig-cf/ludwig/files/3914101/input_simpleshear.txt)

**Comment by kevinstratford** [comment]
OK. The parameters in the file look reasonable I think.

The capillary number looks like Ca = 0.4, so you would expect
a certain deformation.

One might worry that the droplet size is quite close to the system
size in the vorticity direction (z here); not quite sure why you have
choosen this system. I might be tempted to start in two dimensions if I was doing this....
