### ISSUE TITLE
Symmetric stress via relaxation

### ISSUE THREAD

**Issue by kevinstratford** [ludwig-cf/ludwig#64]
Add some comments on this to the documentation, please.

**Comment by kevinstratford** [comment]
The appropriate input key to move forcing from the symmetric part of
the stress tensor to the collision stage (rather than computing the force
as the divergence of the stress) is:

fe_use_stress_relaxation yes

For the liquid crystal case, the antisymmetric stress contributes through
the divergence as normal.

See, e.g., tests/regression/d3q19-short/serial-drop-lc3.inp

**Comment by ohenrich** [comment]
I think something is not quite working here as I get the identical output. I noted that the test uses the droplet FE functional and the 3d_7pt_fluid stencil. I send my input file in a moment.

**Comment by ohenrich** [comment]
I found the problem: This option wasn't enabled for FE lc_blue_phase. 
I encountered another one: With this option enabled I think the stress is calculated twice. Once in fe_lc_str_symm and fe_lc_str_anti, an another time in fe_lc_compute_stress, which I think should not be called anymore if the stress is split into symmetric and antisymmetric part.

**Comment by ohenrich** [comment]
Anther point: There is no vectorised version of fe_lc_str_symm and fe_lc_str_anti in blue_phase.c. But this is easy to rectify once we are clear on the function pointers.

**Comment by kevinstratford** [comment]
I'll make a patch for the initialisation, which is missing.

On the stress calculation, implementations are present in:

fe_lc_str_symm_v()
fe_lc_str_anti_v()

so I think this should provide correct behaviour. There is a separate
(really) vectorised version for the full stress

fe_lc_str_v()

which calls fe_lc_compute_stress(). While this is the same calculation,
it's not called if the stress relaxation switch  is set (phi_force_stress.c).
There, only the anti-symmetric part is computed.

So the stress going into divergence (here via phi_force_colloid.c) is just
the anti-symmetric part.

**Comment by kevinstratford** [comment]
The code is patched at 0.9.3 to allow stress relaxation.

When I have added some information to the documentation, the issue can
be closed.

**Comment by kevinstratford** [comment]
Could you have a look at the new section 2.9 at http://ludwig.epcc.ed.ac.uk/

If it's ok, we can close this ticket.

**Comment by ohenrich** [comment]
This is OK. But it's not included in /docs of the development branch. Is the online section 2 going to replace / augment section 2 in the documentation?

**Comment by kevinstratford** [comment]
The intent is that anything to do with the input should be removed from
the existing latex docs and put online. So I don't really want to add new
stuff to the latex docs.

Ultimately, the whole thing could go online.

**Comment by ohenrich** [comment]
I think going online is a good idea. But it would be good to retain something that can be compiled offline. I used this countless times.

LAMMPS has a markdown style for all documentation and compiles both the online documentation and a pdf out of it. Do you think this could be done?

**Comment by kevinstratford** [comment]
The online stuff is sphinx, which can produce a pdf.

**Comment by ohenrich** [comment]
This is great. Ideally, all the material would make it then online. There are so many little notes and hints that are quite valuable to retain.
