### ISSUE TITLE
Separate isfixedr for XYZ etc

### ISSUE THREAD

**Issue by kevinstratford** [ludwig-cf/ludwig#65]
There are a couple of problems with the implementaton in the
develop branch which I need to fix.

1. The size of the padding colloid.h should be updated
appropriately.

2. Fix for compilation with C++.

There is also an update required in the unit test to allow for
the change in colloid_t definition.

I will also arrange that if both isfixedr and isfixedrxyz appear
in the input, then isfixedr will take precedence and will update
isfixedrxyz[] appropriately.

The test is then only against isfixedrxyz.

**Comment by kevinstratford** [comment]
I'm also going to remove the additional diagnostic output for the time being as this breaks many of the tests.

**Comment by kevinstratford** [comment]
I've also adjusted the structure and I/O calls to allow old files to be read correctly.

**Comment by ohenrich** [comment]
There was a type error in /util/colloid_init.c, which I fixed and checked directly into develop. Please have a look at this. I did tests and it seems everything works fine, so please merge develop with master when you're done.

**Comment by kevinstratford** [comment]
I'm not sure why fe_lc_compute_stress() has changed. This breaks a number of tests. I think we need to review this.

**Comment by ohenrich** [comment]
I know. But we need to discuss on the phone (see email).

**Comment by kevinstratford** [comment]
I've added a mention for this in the web documentation and merged it all into the
master at release 0.10.0. Please let me know if you spot any problems

**Comment by kevinstratford** [comment]
Otherwise, please close the ticket.

**Comment by ohenrich** [comment]
Thanks for this. Can't see any issues, but will open a new ticket in case we encounter some further down the line.
