### ISSUE TITLE
I/O issue with parallel velocity output

### ISSUE THREAD

**Issue by cynthiagc** [ludwig-cf/ludwig#79]
Hi @kevinstratford,

We recently ran a large size (size 400_200_200, grid 8_4_3) simulation of pure fluid channel flow with Ludwig (version 0.8.11), the program reported an error and aborted after outputting the first velocity file. We tried with different values of ‘freq_vel’ in the input file, the program always reported an error when its time step reaches to ‘freq_vel’. The error was shown as ‘[0] malloc(rbuf)’ and ‘application called MPI_Abort(comm=0x84000004, 0) - process 0’ and sometime the value of ‘rho’ became to ‘NaN’ in the out file. We think this error come from ‘io_write_data_s’.

In contrast, we also ran a smaller size simulation (size 200_100_100, grid 8_4_3), the program worked well. So, is there any compatible problem for large size simulation? Could you please give me some suggestions?

We also attached input and out files here.

Thank you in advance!
[input.txt](https://github.com/ludwig-cf/ludwig/files/4486357/input.txt)

[out.txt](https://github.com/ludwig-cf/ludwig/files/4486375/out.txt)

**Comment by kevinstratford** [comment]
I think I see what has happened. As it is, the code will try to allocate a buffer for the entire system on a single node for output. For a large system this will fail.

The answer is to use the parallel I/O feature which prevents the single large allocation. I would also suggest using a binary format. I'll double-check and get back to you with some instructions.
