### ISSUE TITLE
Bond Number

### ISSUE THREAD

**Issue by JaSiddiqui** [ludwig-cf/ludwig#9]
@kevinstratford 
Hello I am using using v.0.6.7 version of ludwig and I tried to reproduce the bond number graph present in your publication "Physical and computational scaling issues in lattice Boltzmann simulations of binary
fluid mixtures" (2005)
But I failed to do so. Particle is not trapping at the interface for any bond number even for very low values.
Can you please give me your input file for that graph? and can you guide me in this regard.

**Comment by kevinstratford** [comment]
Getting the Bond number correct in the code is a little awkward.

I've added a couple of examples with a description. I hope these should help:

tests/regression/d3q19/serial-bond-c01.inp
tests/regression/d3q19/serial-bond-c02.inp

A separate input file is required to run each Bond number.

**Comment by JaSiddiqui** [comment]
Thank you so much. You helped me alot.
